/*
    Imported:   2020-04-26 13:26
    Created By: Casper
    Url:        https://app.codesignal.com/arcade/code-arcade
*/
using NUnit.Framework;
using CodeSignalSolutions;
using CodeSignalSolutions.TheCore.SpringOfIntegration;

namespace TheCore
{
    public class SpringOfIntegration
    {
    /*
        Imported: 2020-04-26 13:26
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/dwA8RtDF86WucuoaQ
    */
    [Test]
    public void arrayConversion()
    {
        Test.Execute(typeof(arrayConversionClass),
            @"inputArray: [1, 2, 3, 4, 5, 6, 7, 8]
            Expected Output: 186",
            @"inputArray: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
            Expected Output: 64",
            @"inputArray: [3, 3, 5, 5]
            Expected Output: 60",
            @"inputArray: [-1, 1, 2, 3, 5, 5, 3, 7]
            Expected Output: 100",
            @"inputArray: [99]
            Expected Output: 99",
            @"inputArray: [99, 1]
            Expected Output: 100",
            @"inputArray: [34, 60, -9, -67, -100, -27, 100, 21]
            Expected Output: -22511"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/MQg7s3dKrP4caN42A
    */
    [Test]
    public void arrayPreviousLess()
    {
        Test.Execute(typeof(arrayPreviousLessClass),
            @"items: [3, 5, 2, 4, 5]
            Expected Output: [-1, 3, -1, 2, 4]",
            @"items: [2, 2, 1, 3, 4, 5, 5, 3]
            Expected Output: [-1, -1, -1, 1, 3, 4, 4, 1]",
            @"items: [3, 2, 1]
            Expected Output: [-1, -1, -1]",
            @"items: [100, 101, 102]
            Expected Output: [-1, 100, 101]",
            @"items: [7, 7, 8, 3, 4, 4, 2, 5, 6, 7, 7]
            Expected Output: [-1, -1, 7, -1, 3, 3, -1, 2, 5, 6, 6]",
            @"items: [68, 135, 101, 170, 125]
            Expected Output: [-1, 68, 68, 101, 101]"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/picP24ieQnuqR4kxJ
    */
    [Test]
    public void pairOfShoes()
    {
        Test.Execute(typeof(pairOfShoesClass),
            @"shoes:
            [[0,21], 
             [1,23], 
             [1,21], 
             [0,23]]
            Expected Output: true",
            @"shoes:
            [[0,21], 
             [1,23], 
             [1,21], 
             [1,23]]
            Expected Output: false",
            @"shoes:
            [[0,23], 
             [1,21], 
             [1,23], 
             [0,21], 
             [1,22], 
             [0,22]]
            Expected Output: true",
            @"shoes:
            [[0,23], 
             [1,21], 
             [1,23], 
             [0,21]]
            Expected Output: true",
            @"shoes:
            [[1,41], 
             [1,40], 
             [1,45], 
             [0,42], 
             [0,42], 
             [0,42]]
            Expected Output: false",
            @"shoes:
            [[1,2], 
             [0,2], 
             [1,1], 
             [0,1], 
             [1,2], 
             [0,1]]
            Expected Output: false",
            @"shoes:
            [[0,100], 
             [1,1], 
             [1,100], 
             [0,1]]
            Expected Output: true",
            @"shoes: [[0,23]]
            Expected Output: false",
            @"shoes:
            [[0,23], 
             [1,23]]
            Expected Output: true",
            @"shoes:
            [[0,23], 
             [1,22]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[1,81], 
             [0,55], 
             [1,92], 
             [0,96], 
             [0,19], 
             [1,94], 
             [1,45], 
             [0,37], 
             [0,55], 
             [1,21], 
             [1,48], 
             [0,53], 
             [0,79], 
             [1,56], 
             [0,10], 
             [0,85], 
             [0,78], 
             [0,66], 
             [0,99], 
             [0,68], 
             [0,28], 
             [1,3], 
             [0,95], 
             [0,52], 
             [1,73], 
             [0,19], 
             [0,38], 
             [1,72], 
             [1,28], 
             [1,9], 
             [1,44], 
             [1,10], 
             [0,75], 
             [0,2], 
             [1,17], 
             [0,4], 
             [0,76], 
             [0,13], 
             [0,80], 
             [1,91], 
             [0,89], 
             [0,4], 
             [0,8], 
             [0,44], 
             [1,36], 
             [1,50], 
             [1,44], 
             [0,12], 
             [0,81], 
             [1,87]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[1,21], 
             [1,54], 
             [0,65], 
             [1,4], 
             [0,93], 
             [0,74], 
             [0,25], 
             [0,70], 
             [1,11], 
             [1,35], 
             [1,7], 
             [0,6], 
             [0,46], 
             [1,45], 
             [0,26], 
             [0,62], 
             [1,59], 
             [0,7], 
             [0,28], 
             [1,34], 
             [0,4], 
             [1,93], 
             [0,89], 
             [1,61], 
             [0,90], 
             [0,29], 
             [1,72], 
             [1,52], 
             [1,87], 
             [1,70], 
             [1,17], 
             [1,85], 
             [0,52], 
             [1,79], 
             [1,61], 
             [1,40], 
             [0,70], 
             [1,21], 
             [0,49], 
             [1,17], 
             [1,6], 
             [0,54], 
             [0,10], 
             [1,29], 
             [1,4], 
             [1,58], 
             [0,63], 
             [0,73], 
             [1,2], 
             [0,87]]
            Expected Output: true",
            @"shoes:
            [[1,1], 
             [1,1], 
             [1,3], 
             [0,2], 
             [0,2], 
             [0,1]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,5], 
             [0,44], 
             [0,81], 
             [0,44], 
             [0,41], 
             [1,58], 
             [1,28], 
             [1,73], 
             [0,42], 
             [1,27], 
             [0,17], 
             [0,68], 
             [0,81], 
             [1,71], 
             [0,5], 
             [1,88], 
             [1,68], 
             [1,30], 
             [1,13], 
             [0,34], 
             [1,79], 
             [0,58], 
             [0,79], 
             [0,31], 
             [1,15], 
             [0,86], 
             [1,52], 
             [1,28], 
             [0,85], 
             [1,88], 
             [0,28], 
             [1,31], 
             [1,34], 
             [0,27], 
             [0,88], 
             [1,86], 
             [0,15], 
             [1,69], 
             [1,44], 
             [1,55], 
             [1,45], 
             [1,17], 
             [0,10], 
             [0,54], 
             [0,82], 
             [0,55], 
             [1,4], 
             [0,97], 
             [0,54], 
             [0,46]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,22], 
             [0,92], 
             [0,31], 
             [1,1], 
             [1,47], 
             [0,2], 
             [1,3], 
             [1,99], 
             [0,88], 
             [1,68], 
             [0,98], 
             [1,82], 
             [0,40], 
             [1,89], 
             [0,43], 
             [1,46], 
             [1,36], 
             [0,61], 
             [0,84], 
             [1,54], 
             [0,45], 
             [0,96], 
             [0,84], 
             [0,11], 
             [1,85], 
             [1,20], 
             [1,28], 
             [1,44], 
             [1,9], 
             [0,100], 
             [0,62], 
             [0,2], 
             [1,95], 
             [0,76], 
             [0,46], 
             [0,24], 
             [0,27], 
             [1,67], 
             [1,75], 
             [0,100], 
             [0,36], 
             [0,81], 
             [0,72], 
             [1,46], 
             [1,28], 
             [1,4], 
             [1,41], 
             [0,86], 
             [1,4], 
             [0,98]]
            Expected Output: false",
            @"shoes:
            [[1,23], 
             [0,22]]
            Expected Output: false",
            @"shoes:
            [[1,25], 
             [0,100], 
             [1,1], 
             [1,1], 
             [0,25], 
             [0,1], 
             [0,100], 
             [1,1], 
             [1,100], 
             [0,25], 
             [0,1], 
             [0,100], 
             [1,25], 
             [0,1]]
            Expected Output: false",
            @"shoes:
            [[1,25], 
             [0,100], 
             [1,1], 
             [1,1], 
             [0,25], 
             [0,1], 
             [0,100], 
             [1,1], 
             [1,100], 
             [0,25], 
             [0,1], 
             [1,1], 
             [0,100], 
             [1,25], 
             [0,1]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,7], 
             [0,4], 
             [0,89], 
             [0,3], 
             [0,52], 
             [0,57], 
             [0,8], 
             [0,13], 
             [0,59], 
             [0,28], 
             [0,40], 
             [0,7], 
             [0,39], 
             [0,24], 
             [0,11], 
             [0,29], 
             [0,12], 
             [0,5], 
             [0,15], 
             [0,12], 
             [0,81], 
             [0,47], 
             [0,77], 
             [0,15], 
             [0,16], 
             [0,73], 
             [0,84], 
             [0,4], 
             [0,60], 
             [0,50], 
             [0,8], 
             [0,67], 
             [0,67], 
             [0,47], 
             [0,3], 
             [0,23], 
             [0,39], 
             [0,22], 
             [0,88], 
             [0,48], 
             [0,11], 
             [0,39], 
             [0,4], 
             [0,7], 
             [0,37], 
             [0,56], 
             [0,72], 
             [0,32], 
             [0,95], 
             [0,42]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,27], 
             [0,7], 
             [0,11], 
             [0,47], 
             [0,54], 
             [0,88], 
             [0,98], 
             [0,100], 
             [0,94], 
             [0,45], 
             [0,70], 
             [0,67], 
             [0,40], 
             [0,98], 
             [0,5], 
             [0,45], 
             [0,37], 
             [0,25], 
             [0,57], 
             [0,55], 
             [0,2], 
             [0,67], 
             [0,24], 
             [0,100], 
             [0,31], 
             [0,20], 
             [0,7], 
             [0,29], 
             [0,94], 
             [0,9], 
             [0,41], 
             [0,93], 
             [0,12], 
             [0,34], 
             [0,39], 
             [0,92], 
             [0,16], 
             [0,86], 
             [0,52], 
             [0,1], 
             [0,18], 
             [0,2], 
             [0,12], 
             [0,78], 
             [0,34], 
             [0,62], 
             [0,58], 
             [0,67], 
             [0,60], 
             [0,10]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,7], 
             [0,85], 
             [0,42], 
             [0,41], 
             [0,37], 
             [0,64], 
             [0,13], 
             [0,70], 
             [0,67], 
             [0,9], 
             [0,19], 
             [0,28], 
             [0,11], 
             [0,86], 
             [0,93], 
             [0,91], 
             [0,45], 
             [0,38], 
             [0,52], 
             [0,21], 
             [0,92], 
             [0,86], 
             [0,87], 
             [0,49], 
             [0,55], 
             [0,11], 
             [0,13], 
             [0,23], 
             [0,65], 
             [0,49], 
             [0,79], 
             [0,85], 
             [0,76], 
             [0,32], 
             [0,87], 
             [0,88], 
             [0,74], 
             [0,80], 
             [0,54], 
             [0,32], 
             [0,56], 
             [0,62], 
             [0,93], 
             [0,31], 
             [0,65], 
             [0,97], 
             [0,69], 
             [0,77], 
             [0,46], 
             [0,47]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,52], 
             [0,51], 
             [0,20], 
             [0,90], 
             [0,86], 
             [0,12], 
             [0,88], 
             [0,55], 
             [0,39], 
             [0,10], 
             [0,50], 
             [0,33], 
             [0,74], 
             [0,16], 
             [0,97], 
             [0,22], 
             [0,17], 
             [0,57], 
             [0,58], 
             [0,39], 
             [0,79], 
             [0,70], 
             [0,75], 
             [0,41], 
             [0,28], 
             [0,97], 
             [0,58], 
             [0,64], 
             [0,66], 
             [0,97], 
             [0,87], 
             [0,99], 
             [0,68], 
             [0,62], 
             [0,56], 
             [0,98], 
             [0,90], 
             [0,73], 
             [0,4], 
             [0,46], 
             [0,12], 
             [0,75], 
             [0,87], 
             [0,40], 
             [0,64], 
             [0,90], 
             [0,59], 
             [0,12], 
             [0,22], 
             [0,84]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,60], 
             [0,91], 
             [0,11], 
             [0,56], 
             [0,5], 
             [0,1], 
             [0,66], 
             [0,100], 
             [0,14], 
             [0,65], 
             [0,95], 
             [0,22], 
             [0,81], 
             [0,19], 
             [0,31], 
             [0,59], 
             [0,61], 
             [0,77], 
             [0,39], 
             [0,80], 
             [0,81], 
             [0,60], 
             [0,43], 
             [0,18], 
             [0,80], 
             [0,47], 
             [0,63], 
             [0,21], 
             [0,30], 
             [0,62], 
             [0,40], 
             [0,42], 
             [0,96], 
             [0,50], 
             [0,72], 
             [0,97], 
             [0,27], 
             [0,21], 
             [0,56], 
             [0,29], 
             [0,24], 
             [0,63], 
             [0,34], 
             [0,38], 
             [0,95], 
             [0,69], 
             [0,98], 
             [0,85], 
             [0,75], 
             [0,86]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,4], 
             [0,73], 
             [0,33], 
             [0,88], 
             [0,76], 
             [0,31], 
             [0,62], 
             [0,30], 
             [0,71], 
             [0,46], 
             [0,31], 
             [0,53], 
             [0,32], 
             [0,39], 
             [0,13], 
             [0,2], 
             [0,31], 
             [0,21], 
             [0,12], 
             [0,32], 
             [0,77], 
             [0,79], 
             [0,63], 
             [0,46], 
             [0,81], 
             [0,15], 
             [0,65], 
             [0,100], 
             [0,17], 
             [0,65], 
             [0,77], 
             [0,14], 
             [0,82], 
             [0,4], 
             [0,1], 
             [0,6], 
             [0,94], 
             [0,51], 
             [0,91], 
             [0,45], 
             [0,35], 
             [0,97], 
             [0,26], 
             [0,84], 
             [0,88], 
             [0,33], 
             [0,62], 
             [0,89], 
             [0,67], 
             [0,76]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,55], 
             [0,54], 
             [0,100], 
             [0,27], 
             [0,31], 
             [0,2], 
             [0,21], 
             [0,57], 
             [0,46], 
             [0,15], 
             [0,85], 
             [0,61], 
             [0,57], 
             [0,34], 
             [0,95], 
             [0,32], 
             [0,33], 
             [0,34], 
             [0,18], 
             [0,18], 
             [0,23], 
             [0,91], 
             [0,26], 
             [0,46], 
             [0,100], 
             [0,55], 
             [0,42], 
             [0,18], 
             [0,7], 
             [0,32], 
             [0,58], 
             [0,88], 
             [0,21], 
             [0,41], 
             [0,70], 
             [0,2], 
             [0,24], 
             [0,4], 
             [0,47], 
             [0,97], 
             [0,88], 
             [0,93], 
             [0,6], 
             [0,90], 
             [0,24], 
             [0,47], 
             [0,7], 
             [0,58], 
             [0,34], 
             [0,14]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,83], 
             [0,51], 
             [0,34], 
             [0,68], 
             [0,18], 
             [0,29], 
             [0,29], 
             [0,43], 
             [0,78], 
             [0,85], 
             [0,17], 
             [0,78], 
             [0,97], 
             [0,52], 
             [0,65], 
             [0,63], 
             [0,34], 
             [0,87], 
             [0,62], 
             [0,60], 
             [0,39], 
             [0,91], 
             [0,31], 
             [0,17], 
             [0,58], 
             [0,87], 
             [0,11], 
             [0,67], 
             [0,34], 
             [0,30], 
             [0,34], 
             [0,41], 
             [0,62], 
             [0,72], 
             [0,4], 
             [0,48], 
             [0,87], 
             [0,54], 
             [0,93], 
             [0,62], 
             [0,84], 
             [0,40], 
             [0,3], 
             [0,64], 
             [0,92], 
             [0,58], 
             [0,8], 
             [0,21], 
             [0,35], 
             [0,97]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,5], 
             [0,58], 
             [0,76], 
             [0,16], 
             [0,42], 
             [0,6], 
             [0,2], 
             [0,7], 
             [0,80], 
             [0,84], 
             [0,42], 
             [0,33], 
             [0,10], 
             [0,92], 
             [0,8], 
             [0,44], 
             [0,45], 
             [0,59], 
             [0,68], 
             [0,24], 
             [0,28], 
             [0,19], 
             [0,95], 
             [0,42], 
             [0,70], 
             [0,16], 
             [0,20], 
             [0,59], 
             [0,100], 
             [0,53], 
             [0,84], 
             [0,67], 
             [0,12], 
             [0,45], 
             [0,46], 
             [0,55], 
             [0,10], 
             [0,53], 
             [0,22], 
             [0,14], 
             [0,49], 
             [0,14], 
             [0,33], 
             [0,21], 
             [0,42], 
             [0,92], 
             [0,61], 
             [0,57], 
             [0,13], 
             [0,4]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,88], 
             [0,4], 
             [0,59], 
             [0,50], 
             [0,22], 
             [0,26], 
             [0,22], 
             [0,67], 
             [0,25], 
             [0,30], 
             [0,95], 
             [0,69], 
             [0,36], 
             [0,59], 
             [0,19], 
             [0,39], 
             [0,13], 
             [0,100], 
             [0,20], 
             [0,43], 
             [0,38], 
             [0,26], 
             [0,49], 
             [0,100], 
             [0,1], 
             [0,90], 
             [0,19], 
             [0,28], 
             [0,75], 
             [0,15], 
             [0,58], 
             [0,1], 
             [0,68], 
             [0,27], 
             [0,87], 
             [0,78], 
             [0,90], 
             [0,76], 
             [0,36], 
             [0,41], 
             [0,13], 
             [0,10], 
             [0,21], 
             [0,63], 
             [0,36], 
             [0,3], 
             [0,55], 
             [0,18], 
             [0,3], 
             [0,91]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,10], 
             [0,52], 
             [0,20], 
             [0,5], 
             [0,40], 
             [0,99], 
             [0,84], 
             [0,7], 
             [0,55], 
             [0,68], 
             [0,82], 
             [0,84], 
             [0,77], 
             [0,89], 
             [0,44], 
             [0,52], 
             [0,35], 
             [0,39], 
             [0,63], 
             [0,94], 
             [0,40], 
             [0,88], 
             [0,100], 
             [0,49], 
             [0,80], 
             [0,75], 
             [0,18], 
             [0,12], 
             [0,34], 
             [0,69], 
             [0,89], 
             [0,67], 
             [0,6], 
             [0,20], 
             [0,35], 
             [0,20], 
             [0,28], 
             [0,2], 
             [0,91], 
             [0,33], 
             [0,75], 
             [0,89], 
             [0,82], 
             [0,32], 
             [0,63], 
             [0,84], 
             [0,84], 
             [0,96], 
             [0,82], 
             [0,78]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,61], 
             [0,82], 
             [0,12], 
             [0,75], 
             [0,7], 
             [0,5], 
             [0,56], 
             [0,33], 
             [0,88], 
             [0,82], 
             [0,81], 
             [0,47], 
             [0,16], 
             [0,99], 
             [0,25], 
             [0,52], 
             [0,72], 
             [0,97], 
             [0,17], 
             [0,56], 
             [0,7], 
             [0,16], 
             [0,4], 
             [0,25], 
             [0,11], 
             [0,70], 
             [0,95], 
             [0,94], 
             [0,87], 
             [0,41], 
             [0,8], 
             [0,53], 
             [0,4], 
             [0,75], 
             [0,36], 
             [0,6], 
             [0,70], 
             [0,7], 
             [0,87], 
             [0,10], 
             [0,100], 
             [0,40], 
             [0,89], 
             [0,37], 
             [0,76], 
             [0,77], 
             [0,57], 
             [0,83], 
             [0,35], 
             [0,65]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,93], 
             [0,87], 
             [0,2], 
             [0,65], 
             [0,58], 
             [0,48], 
             [0,57], 
             [0,37], 
             [0,63], 
             [0,34], 
             [0,28], 
             [0,34], 
             [0,44], 
             [0,42], 
             [0,48], 
             [0,14], 
             [0,33], 
             [0,4], 
             [0,67], 
             [0,67], 
             [0,94], 
             [0,77], 
             [0,6], 
             [0,88], 
             [0,96], 
             [0,43], 
             [0,84], 
             [0,47], 
             [0,52], 
             [0,7], 
             [0,70], 
             [0,32], 
             [0,53], 
             [0,78], 
             [0,36], 
             [0,87], 
             [0,90], 
             [0,30], 
             [0,98], 
             [0,13], 
             [0,66], 
             [0,97], 
             [0,8], 
             [0,6], 
             [0,19], 
             [0,89], 
             [0,18], 
             [0,4], 
             [0,23], 
             [0,71]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,13], 
             [0,5], 
             [0,62], 
             [0,40], 
             [0,2], 
             [0,41], 
             [0,46], 
             [0,41], 
             [0,51], 
             [0,80], 
             [0,80], 
             [0,26], 
             [0,38], 
             [0,69], 
             [0,18], 
             [0,25], 
             [0,63], 
             [0,35], 
             [0,16], 
             [0,29], 
             [0,30], 
             [0,11], 
             [0,13], 
             [0,100], 
             [0,83], 
             [0,9], 
             [0,29], 
             [0,15], 
             [0,34], 
             [0,77], 
             [0,24], 
             [0,71], 
             [0,94], 
             [0,20], 
             [0,75], 
             [0,76], 
             [0,55], 
             [0,80], 
             [0,47], 
             [0,37], 
             [0,100], 
             [0,81], 
             [0,24], 
             [0,36], 
             [0,8], 
             [0,34], 
             [0,77], 
             [0,48], 
             [0,7], 
             [0,83]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,13], 
             [0,88], 
             [0,32], 
             [0,55], 
             [0,27], 
             [0,59], 
             [0,100], 
             [0,30], 
             [0,93], 
             [0,28], 
             [0,62], 
             [0,92], 
             [0,53], 
             [0,99], 
             [0,95], 
             [0,91], 
             [0,37], 
             [0,80], 
             [0,13], 
             [0,65], 
             [0,67], 
             [0,12], 
             [0,58], 
             [0,22], 
             [0,28], 
             [0,6], 
             [0,37], 
             [0,76], 
             [0,6], 
             [0,67], 
             [0,2], 
             [0,50], 
             [0,90], 
             [0,35], 
             [0,94], 
             [0,23], 
             [0,22], 
             [0,58], 
             [0,99], 
             [0,85], 
             [0,70], 
             [0,75], 
             [0,67], 
             [0,47], 
             [0,73], 
             [0,14], 
             [0,4], 
             [0,90], 
             [0,65], 
             [0,72]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,2], 
             [0,39], 
             [0,37], 
             [0,38], 
             [0,91], 
             [0,76], 
             [0,51], 
             [0,50], 
             [0,73], 
             [0,72], 
             [0,12], 
             [0,86], 
             [0,86], 
             [0,100], 
             [0,4], 
             [0,45], 
             [0,55], 
             [0,5], 
             [0,70], 
             [0,12], 
             [0,27], 
             [0,65], 
             [0,62], 
             [0,3], 
             [0,41], 
             [0,69], 
             [0,64], 
             [0,92], 
             [0,7], 
             [0,46], 
             [0,34], 
             [0,93], 
             [0,90], 
             [0,52], 
             [0,80], 
             [0,78], 
             [0,72], 
             [0,76], 
             [0,53], 
             [0,13], 
             [0,92], 
             [0,97], 
             [0,95], 
             [0,2], 
             [0,52], 
             [0,83], 
             [0,62], 
             [0,39], 
             [0,51], 
             [0,56]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,10], 
             [0,48], 
             [0,94], 
             [0,74], 
             [0,66], 
             [0,91], 
             [0,87], 
             [0,28], 
             [0,45], 
             [0,50], 
             [0,74], 
             [0,14], 
             [0,67], 
             [0,41], 
             [0,89], 
             [0,88], 
             [0,72], 
             [0,50], 
             [0,85], 
             [0,85], 
             [0,24], 
             [0,87], 
             [0,22], 
             [0,34], 
             [0,70], 
             [0,82], 
             [0,4], 
             [0,2], 
             [0,75], 
             [0,6], 
             [0,26], 
             [0,87], 
             [0,75], 
             [0,99], 
             [0,39], 
             [0,26], 
             [0,27], 
             [0,43], 
             [0,53], 
             [0,76], 
             [0,7], 
             [0,5], 
             [0,94], 
             [0,77], 
             [0,5], 
             [0,48], 
             [0,76], 
             [0,12], 
             [0,82], 
             [0,2]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,83], 
             [0,29], 
             [0,75], 
             [0,9], 
             [0,28], 
             [0,12], 
             [0,46], 
             [0,29], 
             [0,92], 
             [0,95], 
             [0,17], 
             [0,14], 
             [0,89], 
             [0,91], 
             [0,43], 
             [0,16], 
             [0,99], 
             [0,28], 
             [0,77], 
             [0,23], 
             [0,10], 
             [0,43], 
             [0,23], 
             [0,11], 
             [0,85], 
             [0,90], 
             [0,53], 
             [0,44], 
             [0,31], 
             [0,17], 
             [0,15], 
             [0,5], 
             [0,48], 
             [0,34], 
             [0,95], 
             [0,25], 
             [0,42], 
             [0,13], 
             [0,13], 
             [0,59], 
             [0,72], 
             [0,85], 
             [0,44], 
             [0,58], 
             [0,67], 
             [0,16], 
             [0,56], 
             [0,17], 
             [0,97], 
             [0,14]]
            Expected Output: true",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,15], 
             [0,43], 
             [0,61], 
             [0,31], 
             [0,67], 
             [0,96], 
             [0,2], 
             [0,4], 
             [0,40], 
             [0,86], 
             [0,88], 
             [0,100], 
             [0,55], 
             [0,34], 
             [0,36], 
             [0,17], 
             [0,79], 
             [0,3], 
             [0,40], 
             [0,13], 
             [0,65], 
             [0,33], 
             [0,15], 
             [0,59], 
             [0,43], 
             [0,49], 
             [0,45], 
             [0,37], 
             [0,77], 
             [0,78], 
             [0,14], 
             [0,79], 
             [0,13], 
             [0,69], 
             [0,71], 
             [0,35], 
             [0,44], 
             [0,84], 
             [0,55], 
             [0,86], 
             [0,69], 
             [0,3], 
             [0,58], 
             [0,76], 
             [0,45], 
             [0,60], 
             [0,11], 
             [0,49], 
             [0,55], 
             [0,13]]
            Expected Output: false",
            @"The test case is too large and is shown truncated
            shoes:
            [[0,100], 
             [0,73], 
             [0,60], 
             [0,17], 
             [0,51], 
             [0,22], 
             [0,96], 
             [0,92], 
             [0,22], 
             [0,37], 
             [0,21], 
             [0,87], 
             [0,54], 
             [0,95], 
             [0,4], 
             [0,75], 
             [0,47], 
             [0,83], 
             [0,30], 
             [0,68], 
             [0,82], 
             [0,23], 
             [0,7], 
             [0,20], 
             [0,62], 
             [0,7], 
             [0,48], 
             [0,84], 
             [0,11], 
             [0,67], 
             [0,64], 
             [0,98], 
             [0,37], 
             [0,99], 
             [0,65], 
             [0,100], 
             [0,19], 
             [0,32], 
             [0,78], 
             [0,65], 
             [0,46], 
             [0,16], 
             [0,74], 
             [0,80], 
             [0,45], 
             [0,31], 
             [0,66], 
             [0,63], 
             [0,7], 
             [0,65]]
            Expected Output: true",
            @"shoes:
            [[0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100]]
            Expected Output: true",
            @"shoes:
            [[0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [0,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100], 
             [1,100]]
            Expected Output: false"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/6ceKutpnCs4LzBKgf
    */
    [Test]
    public void combs()
    {
        Test.Execute(typeof(combsClass),
            @"comb1: ""*..*""
            comb2: ""*.*""
            Expected Output: 5",
            @"comb1: ""*...*""
            comb2: ""*.*""
            Expected Output: 5",
            @"comb1: ""*..*.*""
            comb2: ""*.***""
            Expected Output: 9",
            @"comb1: ""*.*""
            comb2: ""*.*""
            Expected Output: 4",
            @"comb1: ""*.**""
            comb2: ""*.*""
            Expected Output: 5"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/6QDtjNr3WoL5W4Kvo
    */
    [Test]
    public void stringsCrossover()
    {
        Test.Execute(typeof(stringsCrossoverClass),
            @"inputArray:
            [""abc"", 
             ""aaa"", 
             ""aba"", 
             ""bab""]
            result: ""bbb""
            Expected Output: 2",
            @"inputArray:
            [""aacccc"", 
             ""bbcccc""]
            result: ""abdddd""
            Expected Output: 0",
            @"inputArray:
            [""a"", 
             ""b"", 
             ""c"", 
             ""d"", 
             ""e""]
            result: ""c""
            Expected Output: 4",
            @"inputArray:
            [""aa"", 
             ""ab"", 
             ""ba""]
            result: ""bb""
            Expected Output: 1",
            @"inputArray:
            [""a"", 
             ""b"", 
             ""c"", 
             ""d"", 
             ""e""]
            result: ""f""
            Expected Output: 0",
            @"inputArray:
            [""aaa"", 
             ""aaa""]
            result: ""aaa""
            Expected Output: 1"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/tKwbrKAQhoCZFqg33
    */
    [Test]
    public void cyclicString()
    {
        Test.Execute(typeof(cyclicStringClass),
            @"s: ""cabca""
            Expected Output: 3",
            @"s: ""aba""
            Expected Output: 2",
            @"s: ""ccccccccccc""
            Expected Output: 1",
            @"s: ""bcaba""
            Expected Output: 5",
            @"s: ""abacabaabacab""
            Expected Output: 7",
            @"s: ""aab""
            Expected Output: 3",
            @"s: ""abaaba""
            Expected Output: 3",
            @"s: ""zazazaza""
            Expected Output: 2",
            @"s: ""abbaab""
            Expected Output: 4"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/PSeEALZTxd93zBHS7
    */
    [Test]
    public void beautifulText()
    {
        Test.Execute(typeof(beautifulTextClass),
            @"inputString: ""Look at this example of a correct text""
            l: 5
            r: 15
            Expected Output: true",
            @"inputString: ""abc def ghi""
            l: 4
            r: 10
            Expected Output: false",
            @"inputString: ""a a a a a a a a""
            l: 1
            r: 10
            Expected Output: true",
            @"inputString: ""ab cd fg xyz""
            l: 1
            r: 5
            Expected Output: false",
            @"inputString: ""aa aa aaaaa aaaaa aaaaa""
            l: 6
            r: 11
            Expected Output: true",
            @"inputString: ""aa aa aaaaa aaaaa aaaaa""
            l: 5
            r: 10
            Expected Output: true",
            @"inputString: ""aa aa aaaaa aaaaa aaaaa""
            l: 6
            r: 10
            Expected Output: false",
            @"inputString: ""aaa aaaaaaa""
            l: 3
            r: 10
            Expected Output: false",
            @"inputString: ""dht skq dkg""
            l: 4
            r: 10
            Expected Output: false",
            @"inputString: ""skspv iakqh ygzwz ntkmi xqhpj""
            l: 3
            r: 7
            Expected Output: true",
            @"inputString: ""skspv iakqh ygzwz ntkmi xqhpj""
            l: 8
            r: 9
            Expected Output: false"
        );
    }
    /*
        Imported: 2020-04-26 13:27
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/Hb9Cppx4pCY4d8J5P
    */
    [Test]
    public void runnersMeetings()
    {
        Test.Execute(typeof(runnersMeetingsClass),
            @"startPosition: [1, 4, 2]
            speed: [27, 18, 24]
            Expected Output: 3",
            @"startPosition: [1, 4, 2]
            speed: [5, 6, 2]
            Expected Output: 2",
            @"startPosition: [1, 2, 3]
            speed: [1, 1, 1]
            Expected Output: -1",
            @"startPosition: [1, 1000]
            speed: [23, 22]
            Expected Output: 2",
            @"startPosition: [-2, 0, 2, 4]
            speed: [6, 5, 4, 3]
            Expected Output: 4",
            @"startPosition: [-2, 0, 2, 4]
            speed: [6, 5, 4, 2]
            Expected Output: 3"
        );
    }
    /*
        Imported: 2020-04-26 13:28
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/FvMZwyYRsGaA7Q3A8
    */
    [Test]
    public void christmasTree()
    {
        Test.Execute(typeof(christmasTreeClass),
            @"levelNum: 1
            levelHeight: 3
            Expected Output: [""    *"", 
             ""    *"", 
             ""   ***"", 
             ""  *****"", 
             "" *******"", 
             ""*********"", 
             ""   ***""]",
            @"levelNum: 2
            levelHeight: 4
            Expected Output: [""      *"", 
             ""      *"", 
             ""     ***"", 
             ""    *****"", 
             ""   *******"", 
             ""  *********"", 
             "" ***********"", 
             ""   *******"", 
             ""  *********"", 
             "" ***********"", 
             ""*************"", 
             ""    *****"", 
             ""    *****""]",
            @"levelNum: 4
            levelHeight: 8
            Expected Output: [""            *"", 
             ""            *"", 
             ""           ***"", 
             ""          *****"", 
             ""         *******"", 
             ""        *********"", 
             ""       ***********"", 
             ""      *************"", 
             ""     ***************"", 
             ""    *****************"", 
             ""   *******************"", 
             ""         *******"", 
             ""        *********"", 
             ""       ***********"", 
             ""      *************"", 
             ""     ***************"", 
             ""    *****************"", 
             ""   *******************"", 
             ""  *********************"", 
             ""        *********"", 
             ""       ***********"", 
             ""      *************"", 
             ""     ***************"", 
             ""    *****************"", 
             ""   *******************"", 
             ""  *********************"", 
             "" ***********************"", 
             ""       ***********"", 
             ""      *************"", 
             ""     ***************"", 
             ""    *****************"", 
             ""   *******************"", 
             ""  *********************"", 
             "" ***********************"", 
             ""*************************"", 
             ""        *********"", 
             ""        *********"", 
             ""        *********"", 
             ""        *********""]",
            @"levelNum: 8
            levelHeight: 5
            Expected Output: [""             *"", 
             ""             *"", 
             ""            ***"", 
             ""           *****"", 
             ""          *******"", 
             ""         *********"", 
             ""        ***********"", 
             ""       *************"", 
             ""          *******"", 
             ""         *********"", 
             ""        ***********"", 
             ""       *************"", 
             ""      ***************"", 
             ""         *********"", 
             ""        ***********"", 
             ""       *************"", 
             ""      ***************"", 
             ""     *****************"", 
             ""        ***********"", 
             ""       *************"", 
             ""      ***************"", 
             ""     *****************"", 
             ""    *******************"", 
             ""       *************"", 
             ""      ***************"", 
             ""     *****************"", 
             ""    *******************"", 
             ""   *********************"", 
             ""      ***************"", 
             ""     *****************"", 
             ""    *******************"", 
             ""   *********************"", 
             ""  ***********************"", 
             ""     *****************"", 
             ""    *******************"", 
             ""   *********************"", 
             ""  ***********************"", 
             "" *************************"", 
             ""    *******************"", 
             ""   *********************"", 
             ""  ***********************"", 
             "" *************************"", 
             ""***************************"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****"", 
             ""           *****""]",
            @"levelNum: 3
            levelHeight: 3
            Expected Output: [""      *"", 
             ""      *"", 
             ""     ***"", 
             ""    *****"", 
             ""   *******"", 
             ""  *********"", 
             ""   *******"", 
             ""  *********"", 
             "" ***********"", 
             ""  *********"", 
             "" ***********"", 
             ""*************"", 
             ""     ***"", 
             ""     ***"", 
             ""     ***""]",
            @"levelNum: 4
            levelHeight: 6
            Expected Output: [""          *"", 
             ""          *"", 
             ""         ***"", 
             ""        *****"", 
             ""       *******"", 
             ""      *********"", 
             ""     ***********"", 
             ""    *************"", 
             ""   ***************"", 
             ""       *******"", 
             ""      *********"", 
             ""     ***********"", 
             ""    *************"", 
             ""   ***************"", 
             ""  *****************"", 
             ""      *********"", 
             ""     ***********"", 
             ""    *************"", 
             ""   ***************"", 
             ""  *****************"", 
             "" *******************"", 
             ""     ***********"", 
             ""    *************"", 
             ""   ***************"", 
             ""  *****************"", 
             "" *******************"", 
             ""*********************"", 
             ""       *******"", 
             ""       *******"", 
             ""       *******"", 
             ""       *******""]"
        );
    }
    /*
        Imported: 2020-04-26 13:28
        By:       Casper
        Url:      https://app.codesignal.com/arcade/code-arcade/spring-of-integration/sqZ9qDTFHXBNrQeLC
    */
    [Test]
    public void fileNaming()
    {
        Test.Execute(typeof(fileNamingClass),
            @"names:
            [""doc"", 
             ""doc"", 
             ""image"", 
             ""doc(1)"", 
             ""doc""]
            Expected Output: [""doc"", 
             ""doc(1)"", 
             ""image"", 
             ""doc(1)(1)"", 
             ""doc(2)""]",
            @"names:
            [""a(1)"", 
             ""a(6)"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a"", 
             ""a""]
            Expected Output: [""a(1)"", 
             ""a(6)"", 
             ""a"", 
             ""a(2)"", 
             ""a(3)"", 
             ""a(4)"", 
             ""a(5)"", 
             ""a(7)"", 
             ""a(8)"", 
             ""a(9)"", 
             ""a(10)"", 
             ""a(11)""]",
            @"names:
            [""dd"", 
             ""dd(1)"", 
             ""dd(2)"", 
             ""dd"", 
             ""dd(1)"", 
             ""dd(1)(2)"", 
             ""dd(1)(1)"", 
             ""dd"", 
             ""dd(1)""]
            Expected Output: [""dd"", 
             ""dd(1)"", 
             ""dd(2)"", 
             ""dd(3)"", 
             ""dd(1)(1)"", 
             ""dd(1)(2)"", 
             ""dd(1)(1)(1)"", 
             ""dd(4)"", 
             ""dd(1)(3)""]",
            @"names:
            [""a"", 
             ""b"", 
             ""cd"", 
             ""b "", 
             ""a(3)""]
            Expected Output: [""a"", 
             ""b"", 
             ""cd"", 
             ""b "", 
             ""a(3)""]",
            @"names:
            [""name"", 
             ""name"", 
             ""name(1)"", 
             ""name(3)"", 
             ""name(2)"", 
             ""name(2)""]
            Expected Output: [""name"", 
             ""name(1)"", 
             ""name(1)(1)"", 
             ""name(3)"", 
             ""name(2)"", 
             ""name(2)(1)""]",
            @"names: []
            Expected Output: []"
        );
    }
    }
}
